2023 02 05 madelein new logging state changes (#56)
* logging state changes in JSON

* commit to get an apk generated

* Adding visual log states

* name changes

* remove CreatePair

* Update GalleryActivity.java

Jack deleted two < apparently responsible for compiler errors:

/home/runner/work/RTFace_Login/RTFace_Login/app/src/main/java/com/example/iris/login1/GalleryActivity.java:2027: error: > expected

<                        logHandler.log("visual_state_gone", "icongall");
> Task :app:compileDebugJavaWithJavac FAILED
                                       ^
/home/runner/work/RTFace_Login/RTFace_Login/app/src/main/java/com/example/iris/login1/GalleryActivity.java:2035: error: > expected

<                        logHandler.log("visual_state_visible", "activity_gal");

* Update GalleryActivity.java

Added missing // after my 2 comments

* Update GalleryActivity.java

deleted "nt" apparently typed by accident

---------

Co-authored-by: JackMostow <JackMostow@users.noreply.github.com>